# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use versions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

workflow:
  rules:
    # prevent run dulicate pipelines
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # always run branch pipeline when merge launched from (note for merged result the pipeline will run again: it needs PREMIUM :-(
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /[NOCI]/
      when: never
    # run when [CI] in msg
    - if: $CI_COMMIT_MESSAGE =~ /[CI]/
      when: always
    # run when [VIP] in msg
    - if: $CI_COMMIT_MESSAGE =~ /[VIP]/
      when: always
    # prevent others
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    # run in other cases like manual trig and merge finished
    - when: always

variables:
  # set to local to run at local server
  BUILD_RUNNER: remote

image: qibin2020/dss-base

stages:
  - build
  - test
  - post

build with ccache:
  stage: build
  script:
    - ./Automaton/build.sh
  artifacts:
    expire_in: 1 week
    paths:
      - "install/*"
      - "test/*"
  cache:
    paths:
      - "build/ccache/*"

# run tests using the binary built before
# we use a central script to tun all the test, or it could be decomposed later
test simu and ana:
  stage: test
  dependencies: 
    - build with ccache
  script:
    - ./Automaton/test.sh
  artifacts:
    when: always
    paths:
      - "test/*"

ci write wiki:
  stage: post
  dependencies: 
    - test simu and ana
  script:
    - ./Automaton/make_wiki.sh
  artifacts:
    when: always
    paths:
      - "test/DSS.wiki.log"
      - "test/*.md"
      - "test/*.upload"
  rules:
    - if:  $CI_COMMIT_MESSAGE =~ /[NOWIKI]/
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE !~ /[WIKI]/
      when: never
    - if:  $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
      when: never
    # run in other cases like manual trig and merge finished
    - when: always