#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
#
# Add icons of general interest
#
#/control/execute icons.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
#/gui/addButton run run1 "/control/execute run1.mac"
#/gui/addButton run run2 "/control/execute run2.mac"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "1 GeV"   "/gun/energy 1 GeV"
/gui/addButton gun "5 GeV"   "/gun/energy 5 GeV"
/gui/addButton gun "10 GeV"  "/gun/energy 10 GeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
#
# Field menu :
/gui/addMenu field Field
/gui/addButton field "off"       "/DP/det/setField 0.0 tesla"
/gui/addButton field "0.2 tesla" "/DP/det/setField 0.2 tesla"
/gui/addButton field "2.0 tesla" "/DP/det/setField 2.0 tesla"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"

####### Detector Settings ########
/DP/det/setTByField                 -1.5 tesla
/DP/det/setRByField                 -0.5 tesla
#/DP/det/ifHCAL                      1
#/DP/det/ifECAL                      1
# Add Tagging Tracker (addNewPos.z must be symmetric)
#/DP/det/tagTrk/addNewSize          10 20 0.01 cm
#/DP/det/tagTrk/addNewPos           0 0 -10 cm
#/DP/det/tagTrk/addNewSize          10 20 0.01 cm
#/DP/det/tagTrk/addNewPos           0 0 0 cm
#/DP/det/tagTrk/addNewSize          10 20 0.01 cm
#/DP/det/tagTrk/addNewPos           0 0 10 cm
# Add Recoil Tracker (addNewPos.z must be symmetric)
#/DP/det/recTrk/addNewSize          10 20 0.01 cm
#/DP/det/recTrk/addNewPos           0  0  -15 cm
#/DP/det/recTrk/addNewSize          10 20 0.01 cm
#/DP/det/recTrk/addNewPos           0  0 -5 cm
#/DP/det/recTrk/addNewSize          10 20 0.01 cm
#/DP/det/recTrk/addNewPos           0  0  5 cm
#/DP/det/recTrk/addNewSize          10 20 0.01 cm
#/DP/det/recTrk/addNewPos           0  0  15 cm
/DP/det/reConstruct

######## Save Geometry #########
/DP/ifSaveGeometry                  0

########## Biasing ############
/DP/Bias/Process                    GammaToMuPair
/DP/Bias/Factor                     1e10
/DP/Bias/Emin                       1 GeV
/DP/Bias/if_bias_target             1
/DP/Bias/if_bias_ecal               1
/DP/setifBias                       0

########## Filter ############
# HardBrem
/DP/Filter/if_filter_HardBrem       0
/DP/Filter/HardBrem_GammaEmin       2 GeV
/DP/Filter/HardBrem_ScanDistance    20 cm
# Process
/DP/Filter/if_filter_Process        0
/DP/Filter/Process_Name             GammaToMuPair
/DP/Filter/Process_Emin             1 GeV
/DP/Filter/Process_MinScanDistance  -5 mm
/DP/Filter/Process_MaxScanDistance  +600 mm

########## Verbose ############
/tracking/verbose                   0
/event/verbose                      0
/run/verbose                        2

########## Primary Gun ############
/gps/source/multiplevertex          true
/gps/source/intensity               5.
/gps/particle                       e-

#/gps/pos/type                      Beam
#/gps/pos/shape                     Circle
#/gps/pos/centre                    0. 0. -607.5 mm
#/gps/pos/radius                    3. cm
#/gps/pos/sigma_r                   1 cm
#/gps/ang/type                      beam1d
#/gps/ang/rot1                      0 1 0
#/gps/ang/rot2                      1 0 0
#/gps/ang/type                      beam1d
#/gps/ang/sigma_r                   5. deg
#/gps/ene/type                      Gauss
#/gps/ene/mono                      4 GeV
#/gps/ene/sigma                     0.1 GeV

/gps/ene/mono                       8 GeV
/gps/direction                      0. 0. 1.
/gps/position                       0. 0.01 -610. mm

########## Other Setting ############
/DP/Event/StartID                   0
/DP/Event/NbEvent                   10000

/DP/Engine/randomSeed               1051
#/random/resetEngineFrom            currentEvent.rndm