# Recursively Find Algorithm headers
MACRO(HEADER_DIRECTORIES return_list return_file search_directory)
    FILE(GLOB_RECURSE new_list ${search_directory}/*/include/*.h)
    SET(dir_list "")
    SET(file_list "")
    FOREACH (file_path ${new_list})
        GET_FILENAME_COMPONENT(file_dir ${file_path} PATH)
        get_filename_component(dir_path ${file_dir} DIRECTORY)
        SET(dir_list ${dir_list} ${dir_path})
    ENDFOREACH ()
    LIST(REMOVE_DUPLICATES dir_list)
    LIST(REMOVE_DUPLICATES new_list)
    SET(${return_list} ${dir_list})
    SET(${return_file} ${new_list})
ENDMACRO()

MACRO(HEADER_DIRECTORIES_GENFIT2 return_list return_file search_directory)
    FILE(GLOB_RECURSE new_list ${search_directory}/*/include/*.h)
    SET(dir_list "")
    SET(file_list "")
    FOREACH (file_path ${new_list})
        get_filename_component(dir_path ${file_path} DIRECTORY)
        SET(dir_list ${dir_list} ${dir_path})
    ENDFOREACH ()
    LIST(REMOVE_DUPLICATES dir_list)
    LIST(REMOVE_DUPLICATES new_list)
    SET(${return_list} ${dir_list})
    SET(${return_file} ${new_list})
ENDMACRO()
